Python 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)]
matplotlib 1.3.0
Tkinter $Revision: 81008 $
ttk 0.3.1
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1470, in __call__
  File "epocs.py", line 3543, in RegionUpdate
TypeError: 'float' object has no attribute '__getitem__'
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1470, in __call__
  File "epocs.py", line 3576, in RegionUpdate
  File "matplotlib\artist.pyc", line 134, in remove
  File "matplotlib\axes.pyc", line 1564, in <lambda>
ValueError: list.remove(x): x not in list
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1470, in __call__
  File "epocs.py", line 3540, in RegionUpdate
  File "matplotlib\artist.pyc", line 134, in remove
  File "matplotlib\axes.pyc", line 1564, in <lambda>
ValueError: list.remove(x): x not in list
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1470, in __call__
  File "epocs.py", line 3576, in RegionUpdate
  File "matplotlib\artist.pyc", line 134, in remove
  File "matplotlib\axes.pyc", line 1564, in <lambda>
ValueError: list.remove(x): x not in list
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1470, in __call__
  File "epocs.py", line 3540, in RegionUpdate
  File "matplotlib\artist.pyc", line 134, in remove
  File "matplotlib\axes.pyc", line 1564, in <lambda>
ValueError: list.remove(x): x not in list
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1470, in __call__
  File "epocs.py", line 3576, in RegionUpdate
  File "matplotlib\artist.pyc", line 134, in remove
  File "matplotlib\axes.pyc", line 1564, in <lambda>
ValueError: list.remove(x): x not in list
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1470, in __call__
  File "epocs.py", line 3576, in RegionUpdate
  File "matplotlib\artist.pyc", line 134, in remove
  File "matplotlib\axes.pyc", line 1564, in <lambda>
ValueError: list.remove(x): x not in list
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1470, in __call__
  File "epocs.py", line 3576, in RegionUpdate
  File "matplotlib\artist.pyc", line 134, in remove
  File "matplotlib\axes.pyc", line 1564, in <lambda>
ValueError: list.remove(x): x not in list
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1470, in __call__
  File "epocs.py", line 3576, in RegionUpdate
  File "matplotlib\artist.pyc", line 134, in remove
  File "matplotlib\axes.pyc", line 1564, in <lambda>
ValueError: list.remove(x): x not in list
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1470, in __call__
  File "epocs.py", line 3576, in RegionUpdate
  File "matplotlib\artist.pyc", line 134, in remove
  File "matplotlib\axes.pyc", line 1564, in <lambda>
ValueError: list.remove(x): x not in list
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1470, in __call__
  File "epocs.py", line 3576, in RegionUpdate
  File "matplotlib\artist.pyc", line 134, in remove
  File "matplotlib\axes.pyc", line 1564, in <lambda>
ValueError: list.remove(x): x not in list
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1470, in __call__
  File "epocs.py", line 3576, in RegionUpdate
  File "matplotlib\artist.pyc", line 134, in remove
  File "matplotlib\axes.pyc", line 1564, in <lambda>
ValueError: list.remove(x): x not in list
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1470, in __call__
  File "epocs.py", line 3576, in RegionUpdate
  File "matplotlib\artist.pyc", line 134, in remove
  File "matplotlib\axes.pyc", line 1564, in <lambda>
ValueError: list.remove(x): x not in list
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1470, in __call__
  File "epocs.py", line 3576, in RegionUpdate
  File "matplotlib\artist.pyc", line 134, in remove
  File "matplotlib\axes.pyc", line 1564, in <lambda>
ValueError: list.remove(x): x not in list
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1470, in __call__
  File "epocs.py", line 3576, in RegionUpdate
  File "matplotlib\artist.pyc", line 134, in remove
  File "matplotlib\axes.pyc", line 1564, in <lambda>
ValueError: list.remove(x): x not in list
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1470, in __call__
  File "epocs.py", line 3576, in RegionUpdate
  File "matplotlib\artist.pyc", line 134, in remove
  File "matplotlib\axes.pyc", line 1564, in <lambda>
ValueError: list.remove(x): x not in list
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1470, in __call__
  File "epocs.py", line 3576, in RegionUpdate
  File "matplotlib\artist.pyc", line 134, in remove
  File "matplotlib\axes.pyc", line 1564, in <lambda>
ValueError: list.remove(x): x not in list
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1470, in __call__
  File "epocs.py", line 3576, in RegionUpdate
  File "matplotlib\artist.pyc", line 134, in remove
  File "matplotlib\axes.pyc", line 1564, in <lambda>
ValueError: list.remove(x): x not in list
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1470, in __call__
  File "epocs.py", line 3576, in RegionUpdate
  File "matplotlib\artist.pyc", line 134, in remove
  File "matplotlib\axes.pyc", line 1564, in <lambda>
ValueError: list.remove(x): x not in list
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1470, in __call__
  File "epocs.py", line 3576, in RegionUpdate
  File "matplotlib\artist.pyc", line 134, in remove
  File "matplotlib\axes.pyc", line 1564, in <lambda>
ValueError: list.remove(x): x not in list
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1470, in __call__
  File "epocs.py", line 3576, in RegionUpdate
  File "matplotlib\artist.pyc", line 134, in remove
  File "matplotlib\axes.pyc", line 1564, in <lambda>
ValueError: list.remove(x): x not in list
